### ISSUE TITLE
Errors in Marketing Automation / XConnect

### ISSUE THREAD

**Issue by butterflycoder333** [mtelligent/SitecoreWebPushNotifications#2]
Hi there David,
We've managed to fork the code base and setup a 9.2 version. But we're having a few issues with the models in xconnect.
After deployment the MA service goes into a reboot cycle due to an error relating to the custom model.
`This configuration has not been initialized. Please call the initialize method before using it.`

Just wondered if you have encountered this previously with your 9.3 implementation or might have any pointers for us around this? On removing the custom model files from root and webjobs, the services happily run again. Looks like a DI issue from the stack trace, but was hoping you may be able to provide some much needed wisdom here.

Full stack trace is as follows:
```
[11/02/2020 22:56:33 > b4a256: INFO] Starting Marketing Automation Engine...
[11/02/2020 22:56:36 > b4a256: INFO] 2020-11-03 09:56:36 ERR Error initializing XConnect client.
[11/02/2020 22:56:36 > b4a256: INFO] System.AggregateException: One or more errors occurred. ---> Sitecore.XConnect.XdbCollectionUnavailableException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
[11/02/2020 22:56:36 > b4a256: ERR ] ERROR
ystem.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
[11/02/2020 22:56:36 > b4a256: INFO]    at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
[11/02/2020 22:56:36 > b4a256: ERR ] System.InvalidOperationException: This configuration has not been initialized. Please call the initialize method before using it.
[11/02/2020 22:56:36 > b4a256: INFO]    --- End of inner exception stack trace ---
[11/02/2020 22:56:36 > b4a256: ERR ]    at Sitecore.XConnect.Client.XConnectClientConfiguration.CheckInitialized()
[11/02/2020 22:56:36 > b4a256: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[11/02/2020 22:56:36 > b4a256: ERR ]    at Sitecore.XConnect.Client.XConnectClientConfiguration.get_CurrentModel()
[11/02/2020 22:56:36 > b4a256: INFO]    at Sitecore.Xdb.Common.Web.CommonWebApiClient`1.<ExecuteAsync>d__41.MoveNext()
[11/02/2020 22:56:36 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
[11/02/2020 22:56:36 > b4a256: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[11/02/2020 22:56:36 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
[11/02/2020 22:56:36 > b4a256: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[11/02/2020 22:56:36 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
[11/02/2020 22:56:36 > b4a256: INFO] --- End of stack trace from previous location where exception was thrown ---
[11/02/2020 22:56:36 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
[11/02/2020 22:56:36 > b4a256: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[11/02/2020 22:56:36 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
[11/02/2020 22:56:36 > b4a256: INFO]    at Sitecore.XConnect.Client.WebApi.ConfigurationWebApiClient.<Refresh>d__6.MoveNext()
[11/02/2020 22:56:36 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
[11/02/2020 22:56:36 > b4a256: INFO]    --- End of inner exception stack trace ---
[11/02/2020 22:56:36 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
[11/02/2020 22:56:36 > b4a256: INFO] --- End of stack trace from previous location where exception was thrown ---
[11/02/2020 22:56:36 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
[11/02/2020 22:56:37 > b4a256: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[11/02/2020 22:56:37 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
[11/02/2020 22:56:37 > b4a256: INFO]    at Sitecore.XConnect.Client.XConnectClientConfiguration.<InitializeAsync>d__32.MoveNext()
[11/02/2020 22:56:37 > b4a256: ERR ]    at Sitecore.XConnect.Configuration.Extensions.<>c__DisplayClass24_0.<UseServiceDecorator>b__1(IServiceProvider provider)
[11/02/2020 22:56:37 > b4a256: INFO]    --- End of inner exception stack trace ---
[11/02/2020 22:56:37 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
[11/02/2020 22:56:37 > b4a256: INFO]    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[11/02/2020 22:56:37 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
[11/02/2020 22:56:37 > b4a256: INFO]    at Sitecore.XConnect.Client.Configuration.XConnect.Extensions.ServiceCollectionExtensions.<>c__DisplayClass1_0.<UseXConnectClientConfiguration>b__0(IServiceProvider provider)
[11/02/2020 22:56:37 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
 System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
[11/02/2020 22:56:37 > b4a256: INFO]    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
[11/02/2020 22:56:37 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
[11/02/2020 22:56:37 > b4a256: INFO]    at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
[11/02/2020 22:56:37 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProviderEngineScope scope)
[11/02/2020 22:56:37 > b4a256: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[11/02/2020 22:56:37 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
[11/02/2020 22:56:37 > b4a256: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[11/02/2020 22:56:37 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
[11/02/2020 22:56:37 > b4a256: INFO] --- End of stack trace from previous location where exception was thrown ---
[11/02/2020 22:56:37 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
[11/02/2020 22:56:37 > b4a256: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[11/02/2020 22:56:37 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
[11/02/2020 22:56:37 > b4a256: INFO]    at Sitecore.Xdb.Common.Web.CommonWebApiClient`1.<ExecuteGetAsync>d__36.MoveNext()
[11/02/2020 22:56:37 > b4a256: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
[11/02/2020 22:56:37 > b4a256: INFO] --- End of stack trace from previous location where exception was thrown ---
[11/02/2020 22:56:37 > b4a256: ERR ]    at Sitecore.Xdb.MarketingAutomation.Engine.App.ServiceConfiguration.get_Engine()
[11/02/2020 22:56:37 > b4a256: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[11/02/2020 22:56:37 > b4a256: ERR ]    at Sitecore.Xdb.MarketingAutomation.Engine.App.Program.RunAsConsoleApp(Boolean interactive)
[11/02/2020 22:56:37 > b4a256: INFO]    at Sitecore.XConnect.Client.WebApi.ConfigurationWebApiClient.<Refresh>d__6.MoveNext()
[11/02/2020 22:56:37 > b4a256: INFO]    --- End of inner exception stack trace ---
[11/02/2020 22:56:37 > b4a256: INFO]    at Sitecore.XConnect.Client.WebApi.ConfigurationWebApiClient.<Refresh>d__6.MoveNext()
[11/02/2020 22:56:37 > b4a256: INFO] --- End of stack trace from previous location where exception was thrown ---
[11/02/2020 22:56:37 > b4a256: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[11/02/2020 22:56:37 > b4a256: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[11/02/2020 22:56:37 > b4a256: INFO]    at Sitecore.XConnect.Client.XConnectClientConfiguration.<InitializeAsync>d__32.MoveNext()<---
[11/02/2020 22:56:37 > b4a256: INFO] 
[11/02/2020 22:56:37 > b4a256: INFO] 
[11/02/2020 22:56:37 > b4a256: SYS INFO] Status changed to Success
[11/02/2020 22:56:37 > b4a256: SYS INFO] Process went down, waiting for 60 seconds
[11/02/2020 22:56:37 > b4a256: SYS INFO] Status changed to PendingRestart
```

**Comment by mtelligent** [comment]
Is the fork anywhere public where I could try to take a look? 

Did you downgrade all the dependencies and deploy the same assemblies I listed here but for Sitecore 9.2?: 

https://github.com/mtelligent/SitecoreWebPushNotifications/tree/master/deploy/xConnect/App_Data/jobs/continuous/AutomationEngine ?

That deploy folder shows what went into the zip file that I ended up needing to deploy to get things working. Note that you may be able to omit some of them as it was a process for me to get it to work and I didn't test what I could remove once I got it working.

**Comment by butterflycoder333** [comment]
Thanks for the pointer, I did a rebuild and have now passed that error.
We certainly did what you mention above, but seems like a rebuild and recopy of the SF.Foundation dll was required.

Though now we're hitting one more error, again thought I'd put it past you incase you've seen something similar here.
`2020-11-03 14:37:28.940 +11:00 [Error] Failed to resolve implementation for activity type '3d2ccc0a-5e13-421b-96f2-ee737319532f'
2020-11-03 14:37:28.940 +11:00 [Error] Failed to create an activity instance for activity '645b7ba7-d249-cd5b-9583-9cb694a39b3c' in plan 'cd687dc3-7988-4dc9-817f-b6d81b2c161a'
System.InvalidOperationException: Failed to create an activity instance for activity '645b7ba7-d249-cd5b-9583-9cb694a39b3c' in plan 'cd687dc3-7988-4dc9-817f-b6d81b2c161a'
   at Sitecore.Xdb.MarketingAutomation.Processing.Plan.PlanDriver.CreateActivity(PulseEnrollmentContext pulseEnrollmentContext)`

I can see the implementation type is pointing to `SF.Foundation.PushNotifications.Activities.PushNotification,SF.Foundation.PushNotifications` on the activity item guid above, and have also confirmed that that is certainly in our dll. 

Thanks again

**Comment by mtelligent** [comment]
You may need to publish the Activity Definition Items? 

You can set breakpoints and attach the debugger to the Automation Service to see if it's getting created, but would expect to see error details in the log related to the type if that was the case.

**Comment by butterflycoder333** [comment]
Got it :) The name of the exe is different in 9.2 (maengine.exe) so the related config that repoints the assembly definitions needed renaming also (wasn't able to resolve the 4.0.2.0 version of buffers). Thanks very much for your support on this!
